
import type { Metadata } from "next";
import "./globals.css";
import SWRegistration from "./SWRegistration";

export const metadata: Metadata = {
  title: "Bolus Calc App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
        <SWRegistration/>
      </body>
    </html>
  );
}
